//! Oracle fixture tests -- compare Rust implementations against scipy reference values.
//!
//! Fixture JSON files were generated by scipy with known parameters. We verify
//! that the Rust implementations reproduce the same results within tolerance.

use approx::assert_abs_diff_eq;
use ndarray::Array1;
use serde::Deserialize;

use ferrolearn_numerical::distributions::{
    Beta, ChiSquared, ContinuousDistribution, FDist, Gamma, Normal, StudentsT,
};
use ferrolearn_numerical::interpolate::{BoundaryCondition, CubicSpline};
use ferrolearn_numerical::sparse_eig::{LanczosSolver, WhichEigenvalues};

// ===========================================================================
// Helpers
// ===========================================================================

fn load_fixture<T: serde::de::DeserializeOwned>(name: &str) -> T {
    let path = format!("{}/../fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to read fixture {path}: {e}"));
    serde_json::from_str(&data).unwrap_or_else(|e| panic!("Failed to parse fixture {path}: {e}"))
}

/// Build a sparse CSR matrix from a dense row-major 2D vector.
fn dense_to_sparse(rows: &[Vec<f64>]) -> sprs::CsMat<f64> {
    let n = rows.len();
    let m = rows[0].len();
    let mut indptr = Vec::with_capacity(n + 1);
    let mut indices = Vec::new();
    let mut data = Vec::new();
    indptr.push(0);
    for row in rows {
        for (j, &val) in row.iter().enumerate() {
            if val.abs() > 1e-15 {
                indices.push(j);
                data.push(val);
            }
        }
        indptr.push(indices.len());
    }
    sprs::CsMat::new((n, m), indptr, indices, data)
}

// ===========================================================================
// Fixture schemas
// ===========================================================================

#[derive(Deserialize)]
struct CubicSplineFixture {
    input: CubicSplineInput,
    expected: CubicSplineExpected,
}

#[derive(Deserialize)]
struct CubicSplineInput {
    x_knots: Vec<f64>,
    y_knots: Vec<f64>,
}

#[derive(Deserialize)]
struct CubicSplineExpected {
    eval_points: Vec<f64>,
    eval_values: Vec<f64>,
}

#[derive(Deserialize)]
struct DistributionsFixture {
    expected: DistributionsExpected,
}

#[derive(Deserialize)]
struct DistributionsExpected {
    normal: DistributionData,
    chi_squared: DistributionData,
    f_distribution: DistributionData,
    students_t: DistributionData,
    beta: DistributionData,
    gamma: DistributionData,
}

#[derive(Deserialize)]
struct DistributionData {
    points: Vec<f64>,
    pdf: Vec<f64>,
    cdf: Vec<f64>,
    sf: Vec<f64>,
}

#[derive(Deserialize)]
struct SparseEigshFixture {
    input: SparseEigshInput,
    expected: SparseEigshExpected,
}

#[derive(Deserialize)]
struct SparseEigshInput {
    matrix: Vec<Vec<f64>>,
    n: usize,
}

#[derive(Deserialize)]
struct SparseEigshExpected {
    eigenvalues: Vec<f64>,
    eigenvectors: Vec<Vec<f64>>,
}

// ===========================================================================
// Test 1: Cubic Spline Oracle
// ===========================================================================

#[test]
fn test_cubic_spline_oracle() {
    let fix: CubicSplineFixture = load_fixture("cubic_spline.json");

    let spline = CubicSpline::new(
        &fix.input.x_knots,
        &fix.input.y_knots,
        BoundaryCondition::NotAKnot,
    )
    .expect("CubicSpline::new should succeed on valid knots");

    let computed = spline.eval_array(&fix.expected.eval_points);

    assert_eq!(
        computed.len(),
        fix.expected.eval_values.len(),
        "number of evaluated points must match"
    );

    for (i, (&got, &want)) in computed
        .iter()
        .zip(fix.expected.eval_values.iter())
        .enumerate()
    {
        assert_abs_diff_eq!(got, want, epsilon = 1e-8,);
        // Provide context on failure (assert_abs_diff_eq already panics,
        // but the index helps identify which point failed).
        let _ = i;
    }
}

// ===========================================================================
// Test 2: Distributions Oracle
// ===========================================================================

/// Helper to check pdf/cdf/sf of a distribution against reference data.
fn check_distribution(
    dist: &dyn ContinuousDistribution,
    data: &DistributionData,
    name: &str,
    tol: f64,
) {
    for (i, &x) in data.points.iter().enumerate() {
        assert_abs_diff_eq!(dist.pdf(x), data.pdf[i], epsilon = tol,);

        assert_abs_diff_eq!(dist.cdf(x), data.cdf[i], epsilon = tol,);

        assert_abs_diff_eq!(dist.sf(x), data.sf[i], epsilon = tol,);

        // Verify CDF + SF = 1 as an internal consistency check.
        assert_abs_diff_eq!(dist.cdf(x) + dist.sf(x), 1.0, epsilon = 1e-12,);

        let _ = name;
    }
}

#[test]
fn test_distributions_oracle() {
    let fix: DistributionsFixture = load_fixture("distributions.json");
    let tol = 1e-10;

    // Normal(0, 1)
    let normal = Normal::new(0.0, 1.0).expect("Normal(0,1) should be valid");
    check_distribution(&normal, &fix.expected.normal, "Normal(0,1)", tol);

    // ChiSquared(5)
    let chi2 = ChiSquared::new(5.0).expect("ChiSquared(5) should be valid");
    check_distribution(&chi2, &fix.expected.chi_squared, "ChiSquared(5)", tol);

    // FDist(5, 10)
    let fdist = FDist::new(5.0, 10.0).expect("FDist(5,10) should be valid");
    check_distribution(&fdist, &fix.expected.f_distribution, "FDist(5,10)", tol);

    // StudentsT(10)
    let tdist = StudentsT::new(10.0).expect("StudentsT(10) should be valid");
    check_distribution(&tdist, &fix.expected.students_t, "StudentsT(10)", tol);

    // Beta(2, 5)
    let beta = Beta::new(2.0, 5.0).expect("Beta(2,5) should be valid");
    check_distribution(&beta, &fix.expected.beta, "Beta(2,5)", tol);

    // Gamma(shape=3, rate=0.5) -- scipy uses scale=2, rate=1/scale=0.5
    let gamma = Gamma::new(3.0, 0.5).expect("Gamma(3, 0.5) should be valid");
    check_distribution(&gamma, &fix.expected.gamma, "Gamma(3,0.5)", tol);
}

// ===========================================================================
// Test 3: Sparse Eigsh Oracle
// ===========================================================================

#[test]
fn test_sparse_eigsh_oracle() {
    let fix: SparseEigshFixture = load_fixture("sparse_eigsh.json");

    let n = fix.input.n;
    assert_eq!(fix.input.matrix.len(), n, "matrix must be n x n");

    // Convert dense matrix to sparse CSR.
    let mat = dense_to_sparse(&fix.input.matrix);

    // Compute 3 largest-magnitude eigenvalues using LanczosSolver.
    let solver = LanczosSolver::new(3)
        .with_which(WhichEigenvalues::LargestMagnitude)
        .with_tol(1e-12)
        .with_max_iter(500);
    let result = solver
        .solve_sparse(&mat)
        .expect("Lanczos solver should converge");

    // Sort computed eigenvalues descending.
    let mut computed_evals: Vec<f64> = result.eigenvalues.to_vec();
    computed_evals.sort_by(|a, b| b.partial_cmp(a).unwrap());

    // Expected eigenvalues (already sorted descending from fixture).
    let expected_evals = &fix.expected.eigenvalues;

    assert_eq!(
        computed_evals.len(),
        expected_evals.len(),
        "number of eigenvalues must match"
    );

    for (i, (&got, &want)) in computed_evals.iter().zip(expected_evals.iter()).enumerate() {
        assert_abs_diff_eq!(got, want, epsilon = 1e-8,);
        let _ = i;
    }

    // Verify eigenvectors with sign-flip-aware comparison.
    // Eigenvectors are unique up to a sign flip: v and -v are both valid.
    // For each eigenvector pair, check that either v == v_ref or v == -v_ref.

    // Reconstruct eigenvectors from the fixture as column vectors.
    // fix.expected.eigenvectors is a list of n rows, each of length k.
    let k = expected_evals.len();
    let mut expected_cols: Vec<Array1<f64>> = Vec::with_capacity(k);
    for j in 0..k {
        let col: Vec<f64> = fix.expected.eigenvectors.iter().map(|row| row[j]).collect();
        expected_cols.push(Array1::from_vec(col));
    }

    // Match computed eigenvectors (sorted by eigenvalue) to expected ones.
    // First, get the sorted indices for the computed eigenvalues.
    let mut idx_sorted: Vec<usize> = (0..k).collect();
    {
        let evals = &result.eigenvalues;
        idx_sorted.sort_by(|&a, &b| evals[b].partial_cmp(&evals[a]).unwrap());
    }

    for (j, &col_idx) in idx_sorted.iter().enumerate() {
        let computed_vec = result.eigenvectors.column(col_idx);
        let expected_vec = &expected_cols[j];

        // Determine sign: use dot product to decide the sign convention.
        let dot: f64 = computed_vec
            .iter()
            .zip(expected_vec.iter())
            .map(|(&a, &b)| a * b)
            .sum();
        let sign = if dot >= 0.0 { 1.0 } else { -1.0 };

        for (i, (&got, &want)) in computed_vec.iter().zip(expected_vec.iter()).enumerate() {
            assert_abs_diff_eq!(sign * got, want, epsilon = 1e-6,);
            let _ = i;
        }
    }
}
